#!/usr/bin/env python3
"""Rebuild docs/COMPLETE-INDEX.md from live tree."""
import pathlib, re
from datetime import datetime

ROOT = pathlib.Path('.').resolve()
OUT = ROOT / 'docs/COMPLETE-INDEX.md'
EXCLUDE_DIRS = {'.git', 'node_modules', '.venv', 'ARCHIVE'}
EXCLUDE_FILES = {'COMPLETE-INDEX.md', 'REPO-WORK-PLAN.md'}

def title_of(path: pathlib.Path) -> str:
    for line in path.read_text(errors='ignore').splitlines():
        m = re.match(r'^#+\s*(.+)', line)
        if m:
            t = m.group(1).strip()
            if 'PRICING CROSS-REFERENCE' not in t:
                return t
    return path.name

rows = []
for p in sorted(ROOT.rglob('*.md')):
    if any(d in p.parts for d in EXCLUDE_DIRS):
        continue
    if p.name in EXCLUDE_FILES:
        continue
    rel = str(p.relative_to(ROOT))
    sz = p.stat().st_size
    t = title_of(p)
    rows.append((sz, rel, t))

rows.sort(key=lambda x: x[1])

now = datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')

lines = [
    '# COMPLETE-INDEX.md',
    '',
    f'*Auto-generated by tools/_rebuild_indexes.py — {now}*',
    '',
    '| File | Size | Title |',
    '|------|-----:|-------|',
]
for sz, rel, t in rows:
    lines.append(f'| `{rel}` | {sz:,} | {t} |')
lines.append('')
OUT.write_text('\n'.join(lines), encoding='utf-8')
print(f'wrote {OUT} ({len(rows)} entries)')
